name: Deploy Fullstack App on EC2

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Backend
      - name: Install backend deps
        working-directory: server
        run: npm install

      - name: Backend env
        working-directory: server
        run: echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend
        working-directory: server
        run: /home/ubuntu/.nvm/versions/node/v24.12.0/bin/pm2 restart backend || /home/ubuntu/.nvm/versions/node/v24.12.0/bin/pm2 start index.js --name backend

      # Frontend
      - name: Install frontend deps
        working-directory: client
        run: npm install

      - name: Frontend env
        working-directory: client
        run: echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r client/dist/* /var/www/html/
